### ISSUE TITLE
Can this be used to test against an app running locally? e.g. http://localhost

### ISSUE THREAD

**Issue by githubjosh** [zrrrzzt/gpagespeed#47]

**Comment by zrrrzzt** [comment]
To use this module against your local development environment you will have to do it via solutions like [ngrok](https://ngrok.com/) or [localtunnel](https://localtunnel.github.io/www/).
These will create a unique public url and tunnel the traffic to your local server.

If you don't want to use those, or similar, solutions I would recommend Googles [lighthouse](https://developers.google.com/web/tools/lighthouse/). That will probably give you a much better audit than this module :-)

**Comment by githubjosh** [comment]
Many thanks for the quick response. I'm moving ahead with Lighthouse :)
